language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - bc
      - doxygen
      - expect
      - gettext
      - libncurses5-dev
sudo: false
script:
  - autoreconf
  - ./configure --prefix=$HOME/prefix
  - make -j2
  - make install
  - make test SHOW_INTERACTIVE_LOG=1
notifications:
  irc:
    channels:
      - "irc.oftc.net#fish"
    template:
      - "%{repository}#%{build_number} (%{commit} on %{branch} by %{author}): %{message} Details at %{build_url}"
    use_notice: true
    skip_join: true
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/61821cec3015bf0f8bb1
matrix:
  fast_finish: true
