language: cpp
sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - bc
            - expect
            - gettext
            - libncurses5-dev
        coverity_scan:
          project:
            name: "fish-shell/fish-shell"
            description: "The friendly interactive shell"
          notification_email:
            secure: "lq3AelSInSOqVJI2EZUTrsOrt9ev5c8DHMi7ESyefvv1p+7Qr2gRZmLa+dXLrkPegG+Op9Tykq9zwXRGC4pzC+0OelCKJgqpqkj6LwS8WSamiamAf9ZtPbANwSFMD17f/NTeG/OtBgq6Z87Nur2GEhxmSu3M9IEBOsnOgmCKo84="
          build_command_prepend: "autoreconf; ./configure; make clean"
          build_command:   "make -j 4"
          branch_pattern: coverity_scan_master
  fast_finish: true

script:
  - autoreconf
  - ./configure --prefix=$HOME/prefix || cat config.log
  - make -j2
  - make install
  - make test DESTDIR=$HOME/prefix/ SHOW_INTERACTIVE_LOG=1

notifications:
  # Some items are encrypted so that notifications from other repositories
  # don't flood the official repositories.
  irc:
    channels:
        #- "irc.oftc.net#fish"
        secure: "eRk9KGZ5+mrlD2SoI8yg2Sp8OYrh7YPyGe3WCDQUwTnNgNDII34rbM9a6UOA/l7AeWSNY8joLq5xVLCU4wpFgUcJ11SYIpMnLosZK29OW4ubDOHmdBDvJ971rLgAVG9cXngZtIxEVVxN/jnS1Qr8GKZx4DjkaTMgz1pemb4WxCc="
    template:
      - "%{repository}#%{build_number} (%{commit} on %{branch} by %{author}): %{message} Details at %{build_url}"
    use_notice: true
    skip_join: true
  webhooks:
    urls:
        #- https://webhooks.gitter.im/e/61821cec3015bf0f8bb1
        secure: fPfOmxnC3MCsfR1oocVFeWLawGcRZkn+8fNHlSOeZ+SqqoZfcCHgQTvQ22TqmVl1yvkXbNlaXjo6dbVzTOAh7r7H0bRMEKBVh3dQS7wqjB1sKivpXd8PAS3BTj5MQpGeJzdHnDuwVlwDktGtfHfhGeq1Go/4IosOq8u+6RTe28g=

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "CWLImZSKyXzxuHKInSvV1zK6nFt3zDqTYJ4Ex3OGgKV18pT2dnav7d0ZYe6nottmlYPy802a1rIyCa5vEyQ8Q5OWStnuGP3Tlnzy4zDjd49q3CuspY1zXYOYmMGUoxlOJGjxJAStnDCPNK0T3rAy+0/JMO9x77ezrxtA+i5zMPg="
